output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "backend-db"
  host   = "localhost"
  port   = 5432
  user   = "backend-db"
  pass   = "backend-db"
  schema = "public"
  sslmode = "disable"
  blacklist = ["migrations", "other", "_conduit_version_pgsql"]
