// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm_models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang_server/model"
)

func newConduitVersionPgsql(db *gorm.DB, opts ...gen.DOOption) conduitVersionPgsql {
	_conduitVersionPgsql := conduitVersionPgsql{}

	_conduitVersionPgsql.conduitVersionPgsqlDo.UseDB(db, opts...)
	_conduitVersionPgsql.conduitVersionPgsqlDo.UseModel(&model.ConduitVersionPgsql{})

	tableName := _conduitVersionPgsql.conduitVersionPgsqlDo.TableName()
	_conduitVersionPgsql.ALL = field.NewAsterisk(tableName)
	_conduitVersionPgsql.Versionnumber = field.NewInt32(tableName, "versionnumber")
	_conduitVersionPgsql.Dateofupgrade = field.NewTime(tableName, "dateofupgrade")

	_conduitVersionPgsql.fillFieldMap()

	return _conduitVersionPgsql
}

type conduitVersionPgsql struct {
	conduitVersionPgsqlDo conduitVersionPgsqlDo

	ALL           field.Asterisk
	Versionnumber field.Int32
	Dateofupgrade field.Time

	fieldMap map[string]field.Expr
}

func (c conduitVersionPgsql) Table(newTableName string) *conduitVersionPgsql {
	c.conduitVersionPgsqlDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conduitVersionPgsql) As(alias string) *conduitVersionPgsql {
	c.conduitVersionPgsqlDo.DO = *(c.conduitVersionPgsqlDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conduitVersionPgsql) updateTableName(table string) *conduitVersionPgsql {
	c.ALL = field.NewAsterisk(table)
	c.Versionnumber = field.NewInt32(table, "versionnumber")
	c.Dateofupgrade = field.NewTime(table, "dateofupgrade")

	c.fillFieldMap()

	return c
}

func (c *conduitVersionPgsql) WithContext(ctx context.Context) *conduitVersionPgsqlDo {
	return c.conduitVersionPgsqlDo.WithContext(ctx)
}

func (c conduitVersionPgsql) TableName() string { return c.conduitVersionPgsqlDo.TableName() }

func (c conduitVersionPgsql) Alias() string { return c.conduitVersionPgsqlDo.Alias() }

func (c *conduitVersionPgsql) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conduitVersionPgsql) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["versionnumber"] = c.Versionnumber
	c.fieldMap["dateofupgrade"] = c.Dateofupgrade
}

func (c conduitVersionPgsql) clone(db *gorm.DB) conduitVersionPgsql {
	c.conduitVersionPgsqlDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c conduitVersionPgsql) replaceDB(db *gorm.DB) conduitVersionPgsql {
	c.conduitVersionPgsqlDo.ReplaceDB(db)
	return c
}

type conduitVersionPgsqlDo struct{ gen.DO }

func (c conduitVersionPgsqlDo) Debug() *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Debug())
}

func (c conduitVersionPgsqlDo) WithContext(ctx context.Context) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conduitVersionPgsqlDo) ReadDB() *conduitVersionPgsqlDo {
	return c.Clauses(dbresolver.Read)
}

func (c conduitVersionPgsqlDo) WriteDB() *conduitVersionPgsqlDo {
	return c.Clauses(dbresolver.Write)
}

func (c conduitVersionPgsqlDo) Session(config *gorm.Session) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Session(config))
}

func (c conduitVersionPgsqlDo) Clauses(conds ...clause.Expression) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conduitVersionPgsqlDo) Returning(value interface{}, columns ...string) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conduitVersionPgsqlDo) Not(conds ...gen.Condition) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conduitVersionPgsqlDo) Or(conds ...gen.Condition) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conduitVersionPgsqlDo) Select(conds ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conduitVersionPgsqlDo) Where(conds ...gen.Condition) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conduitVersionPgsqlDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *conduitVersionPgsqlDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c conduitVersionPgsqlDo) Order(conds ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conduitVersionPgsqlDo) Distinct(cols ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conduitVersionPgsqlDo) Omit(cols ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conduitVersionPgsqlDo) Join(table schema.Tabler, on ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conduitVersionPgsqlDo) LeftJoin(table schema.Tabler, on ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conduitVersionPgsqlDo) RightJoin(table schema.Tabler, on ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conduitVersionPgsqlDo) Group(cols ...field.Expr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conduitVersionPgsqlDo) Having(conds ...gen.Condition) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conduitVersionPgsqlDo) Limit(limit int) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conduitVersionPgsqlDo) Offset(offset int) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conduitVersionPgsqlDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conduitVersionPgsqlDo) Unscoped() *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conduitVersionPgsqlDo) Create(values ...*model.ConduitVersionPgsql) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conduitVersionPgsqlDo) CreateInBatches(values []*model.ConduitVersionPgsql, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conduitVersionPgsqlDo) Save(values ...*model.ConduitVersionPgsql) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conduitVersionPgsqlDo) First() (*model.ConduitVersionPgsql, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConduitVersionPgsql), nil
	}
}

func (c conduitVersionPgsqlDo) Take() (*model.ConduitVersionPgsql, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConduitVersionPgsql), nil
	}
}

func (c conduitVersionPgsqlDo) Last() (*model.ConduitVersionPgsql, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConduitVersionPgsql), nil
	}
}

func (c conduitVersionPgsqlDo) Find() ([]*model.ConduitVersionPgsql, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConduitVersionPgsql), err
}

func (c conduitVersionPgsqlDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConduitVersionPgsql, err error) {
	buf := make([]*model.ConduitVersionPgsql, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conduitVersionPgsqlDo) FindInBatches(result *[]*model.ConduitVersionPgsql, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conduitVersionPgsqlDo) Attrs(attrs ...field.AssignExpr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conduitVersionPgsqlDo) Assign(attrs ...field.AssignExpr) *conduitVersionPgsqlDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conduitVersionPgsqlDo) Joins(fields ...field.RelationField) *conduitVersionPgsqlDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conduitVersionPgsqlDo) Preload(fields ...field.RelationField) *conduitVersionPgsqlDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conduitVersionPgsqlDo) FirstOrInit() (*model.ConduitVersionPgsql, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConduitVersionPgsql), nil
	}
}

func (c conduitVersionPgsqlDo) FirstOrCreate() (*model.ConduitVersionPgsql, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConduitVersionPgsql), nil
	}
}

func (c conduitVersionPgsqlDo) FindByPage(offset int, limit int) (result []*model.ConduitVersionPgsql, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conduitVersionPgsqlDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conduitVersionPgsqlDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conduitVersionPgsqlDo) Delete(models ...*model.ConduitVersionPgsql) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conduitVersionPgsqlDo) withDO(do gen.Dao) *conduitVersionPgsqlDo {
	c.DO = *do.(*gen.DO)
	return c
}
