// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFeedback = "feedback"

// Feedback mapped from table <feedback>
type Feedback struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Message   string    `gorm:"column:message;not null" json:"message"`
	Createdat time.Time `gorm:"column:createdat;not null;default:now()" json:"createdat"`
}

// TableName Feedback's table name
func (*Feedback) TableName() string {
	return TableNameFeedback
}
