// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNewsletterParticipation = "newsletter_participation"

// NewsletterParticipation mapped from table <newsletter_participation>
type NewsletterParticipation struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Verifytoken string    `gorm:"column:verifytoken;not null" json:"verifytoken"`
	Firstname   string    `gorm:"column:firstname;not null" json:"firstname"`
	Lastname    string    `gorm:"column:lastname;not null" json:"lastname"`
	Activated   bool      `gorm:"column:activated;not null" json:"activated"`
	Createdat   time.Time `gorm:"column:createdat;not null;default:now()" json:"createdat"`
}

// TableName NewsletterParticipation's table name
func (*NewsletterParticipation) TableName() string {
	return TableNameNewsletterParticipation
}
