// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTrainingTrainer = "training_trainers"

// TrainingTrainer mapped from table <training_trainers>
type TrainingTrainer struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TrainerID  int64 `gorm:"column:trainer_id;not null" json:"trainer_id"`
	TrainingID int64 `gorm:"column:training_id;not null" json:"training_id"`
}

// TableName TrainingTrainer's table name
func (*TrainingTrainer) TableName() string {
	return TableNameTrainingTrainer
}
