// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserTraining = "user_trainings"

// UserTraining mapped from table <user_trainings>
type UserTraining struct {
	ID                int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Validatedfromuser bool  `gorm:"column:validatedfromuser;not null" json:"validatedfromuser"`
	UserID            int64 `gorm:"column:user_id;not null" json:"user_id"`
	TrainingdateID    int64 `gorm:"column:trainingdate_id;not null" json:"trainingdate_id"`
}

// TableName UserTraining's table name
func (*UserTraining) TableName() string {
	return TableNameUserTraining
}
