// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Firstname   string    `gorm:"column:firstname;not null" json:"firstname"`
	Lastname    string    `gorm:"column:lastname;not null" json:"lastname"`
	Loginname   string    `gorm:"column:loginname;not null" json:"loginname"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Password    string    `gorm:"column:password;not null" json:"password"`
	Birthdate   time.Time `gorm:"column:birthdate;not null" json:"birthdate"`
	Lastlogin   time.Time `gorm:"column:lastlogin" json:"lastlogin"`
	Newsletter  bool      `gorm:"column:newsletter;not null" json:"newsletter"`
	Role        string    `gorm:"column:role;not null" json:"role"`
	Externalid  string    `gorm:"column:externalid" json:"externalid"`
	Createdat   time.Time `gorm:"column:createdat;not null;default:now()" json:"createdat"`
	PushtokenID int64     `gorm:"column:pushtoken_id" json:"pushtoken_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
