// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserCredit is an object representing the database table.
type UserCredit struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Createdat time.Time `boil:"createdat" json:"createdat" toml:"createdat" yaml:"createdat"`
	Updatedat time.Time `boil:"updatedat" json:"updatedat" toml:"updatedat" yaml:"updatedat"`
	UserID    int64     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CreditID  int64     `boil:"credit_id" json:"credit_id" toml:"credit_id" yaml:"credit_id"`

	R *userCreditR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userCreditL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserCreditColumns = struct {
	ID        string
	Createdat string
	Updatedat string
	UserID    string
	CreditID  string
}{
	ID:        "id",
	Createdat: "createdat",
	Updatedat: "updatedat",
	UserID:    "user_id",
	CreditID:  "credit_id",
}

var UserCreditTableColumns = struct {
	ID        string
	Createdat string
	Updatedat string
	UserID    string
	CreditID  string
}{
	ID:        "user_credits.id",
	Createdat: "user_credits.createdat",
	Updatedat: "user_credits.updatedat",
	UserID:    "user_credits.user_id",
	CreditID:  "user_credits.credit_id",
}

// Generated where

var UserCreditWhere = struct {
	ID        whereHelperint64
	Createdat whereHelpertime_Time
	Updatedat whereHelpertime_Time
	UserID    whereHelperint64
	CreditID  whereHelperint64
}{
	ID:        whereHelperint64{field: "\"user_credits\".\"id\""},
	Createdat: whereHelpertime_Time{field: "\"user_credits\".\"createdat\""},
	Updatedat: whereHelpertime_Time{field: "\"user_credits\".\"updatedat\""},
	UserID:    whereHelperint64{field: "\"user_credits\".\"user_id\""},
	CreditID:  whereHelperint64{field: "\"user_credits\".\"credit_id\""},
}

// UserCreditRels is where relationship names are stored.
var UserCreditRels = struct {
	Credit string
	User   string
}{
	Credit: "Credit",
	User:   "User",
}

// userCreditR is where relationships are stored.
type userCreditR struct {
	Credit *Credit `boil:"Credit" json:"Credit" toml:"Credit" yaml:"Credit"`
	User   *User   `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userCreditR) NewStruct() *userCreditR {
	return &userCreditR{}
}

func (r *userCreditR) GetCredit() *Credit {
	if r == nil {
		return nil
	}
	return r.Credit
}

func (r *userCreditR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// userCreditL is where Load methods for each relationship are stored.
type userCreditL struct{}

var (
	userCreditAllColumns            = []string{"id", "createdat", "updatedat", "user_id", "credit_id"}
	userCreditColumnsWithoutDefault = []string{"user_id", "credit_id"}
	userCreditColumnsWithDefault    = []string{"id", "createdat", "updatedat"}
	userCreditPrimaryKeyColumns     = []string{"id"}
	userCreditGeneratedColumns      = []string{}
)

type (
	// UserCreditSlice is an alias for a slice of pointers to UserCredit.
	// This should almost always be used instead of []UserCredit.
	UserCreditSlice []*UserCredit
	// UserCreditHook is the signature for custom UserCredit hook methods
	UserCreditHook func(context.Context, boil.ContextExecutor, *UserCredit) error

	userCreditQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userCreditType                 = reflect.TypeOf(&UserCredit{})
	userCreditMapping              = queries.MakeStructMapping(userCreditType)
	userCreditPrimaryKeyMapping, _ = queries.BindMapping(userCreditType, userCreditMapping, userCreditPrimaryKeyColumns)
	userCreditInsertCacheMut       sync.RWMutex
	userCreditInsertCache          = make(map[string]insertCache)
	userCreditUpdateCacheMut       sync.RWMutex
	userCreditUpdateCache          = make(map[string]updateCache)
	userCreditUpsertCacheMut       sync.RWMutex
	userCreditUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userCreditAfterSelectHooks []UserCreditHook

var userCreditBeforeInsertHooks []UserCreditHook
var userCreditAfterInsertHooks []UserCreditHook

var userCreditBeforeUpdateHooks []UserCreditHook
var userCreditAfterUpdateHooks []UserCreditHook

var userCreditBeforeDeleteHooks []UserCreditHook
var userCreditAfterDeleteHooks []UserCreditHook

var userCreditBeforeUpsertHooks []UserCreditHook
var userCreditAfterUpsertHooks []UserCreditHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserCredit) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserCredit) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserCredit) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserCredit) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserCredit) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserCredit) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserCredit) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserCredit) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserCredit) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userCreditAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserCreditHook registers your hook function for all future operations.
func AddUserCreditHook(hookPoint boil.HookPoint, userCreditHook UserCreditHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userCreditAfterSelectHooks = append(userCreditAfterSelectHooks, userCreditHook)
	case boil.BeforeInsertHook:
		userCreditBeforeInsertHooks = append(userCreditBeforeInsertHooks, userCreditHook)
	case boil.AfterInsertHook:
		userCreditAfterInsertHooks = append(userCreditAfterInsertHooks, userCreditHook)
	case boil.BeforeUpdateHook:
		userCreditBeforeUpdateHooks = append(userCreditBeforeUpdateHooks, userCreditHook)
	case boil.AfterUpdateHook:
		userCreditAfterUpdateHooks = append(userCreditAfterUpdateHooks, userCreditHook)
	case boil.BeforeDeleteHook:
		userCreditBeforeDeleteHooks = append(userCreditBeforeDeleteHooks, userCreditHook)
	case boil.AfterDeleteHook:
		userCreditAfterDeleteHooks = append(userCreditAfterDeleteHooks, userCreditHook)
	case boil.BeforeUpsertHook:
		userCreditBeforeUpsertHooks = append(userCreditBeforeUpsertHooks, userCreditHook)
	case boil.AfterUpsertHook:
		userCreditAfterUpsertHooks = append(userCreditAfterUpsertHooks, userCreditHook)
	}
}

// One returns a single userCredit record from the query.
func (q userCreditQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserCredit, error) {
	o := &UserCredit{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_credits")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserCredit records from the query.
func (q userCreditQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserCreditSlice, error) {
	var o []*UserCredit

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserCredit slice")
	}

	if len(userCreditAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserCredit records in the query.
func (q userCreditQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_credits rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userCreditQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_credits exists")
	}

	return count > 0, nil
}

// Credit pointed to by the foreign key.
func (o *UserCredit) Credit(mods ...qm.QueryMod) creditQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreditID),
	}

	queryMods = append(queryMods, mods...)

	return Credits(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserCredit) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadCredit allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userCreditL) LoadCredit(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserCredit interface{}, mods queries.Applicator) error {
	var slice []*UserCredit
	var object *UserCredit

	if singular {
		var ok bool
		object, ok = maybeUserCredit.(*UserCredit)
		if !ok {
			object = new(UserCredit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserCredit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserCredit))
			}
		}
	} else {
		s, ok := maybeUserCredit.(*[]*UserCredit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserCredit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserCredit))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userCreditR{}
		}
		args = append(args, object.CreditID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userCreditR{}
			}

			for _, a := range args {
				if a == obj.CreditID {
					continue Outer
				}
			}

			args = append(args, obj.CreditID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`credits`),
		qm.WhereIn(`credits.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Credit")
	}

	var resultSlice []*Credit
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Credit")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for credits")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for credits")
	}

	if len(creditAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Credit = foreign
		if foreign.R == nil {
			foreign.R = &creditR{}
		}
		foreign.R.UserCredits = append(foreign.R.UserCredits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreditID == foreign.ID {
				local.R.Credit = foreign
				if foreign.R == nil {
					foreign.R = &creditR{}
				}
				foreign.R.UserCredits = append(foreign.R.UserCredits, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userCreditL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserCredit interface{}, mods queries.Applicator) error {
	var slice []*UserCredit
	var object *UserCredit

	if singular {
		var ok bool
		object, ok = maybeUserCredit.(*UserCredit)
		if !ok {
			object = new(UserCredit)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserCredit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserCredit))
			}
		}
	} else {
		s, ok := maybeUserCredit.(*[]*UserCredit)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserCredit)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserCredit))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userCreditR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userCreditR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserCredits = append(foreign.R.UserCredits, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserCredits = append(foreign.R.UserCredits, local)
				break
			}
		}
	}

	return nil
}

// SetCredit of the userCredit to the related item.
// Sets o.R.Credit to related.
// Adds o to related.R.UserCredits.
func (o *UserCredit) SetCredit(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Credit) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_credits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"credit_id"}),
		strmangle.WhereClause("\"", "\"", 2, userCreditPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreditID = related.ID
	if o.R == nil {
		o.R = &userCreditR{
			Credit: related,
		}
	} else {
		o.R.Credit = related
	}

	if related.R == nil {
		related.R = &creditR{
			UserCredits: UserCreditSlice{o},
		}
	} else {
		related.R.UserCredits = append(related.R.UserCredits, o)
	}

	return nil
}

// SetUser of the userCredit to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserCredits.
func (o *UserCredit) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_credits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userCreditPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userCreditR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserCredits: UserCreditSlice{o},
		}
	} else {
		related.R.UserCredits = append(related.R.UserCredits, o)
	}

	return nil
}

// UserCredits retrieves all the records using an executor.
func UserCredits(mods ...qm.QueryMod) userCreditQuery {
	mods = append(mods, qm.From("\"user_credits\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_credits\".*"})
	}

	return userCreditQuery{q}
}

// FindUserCredit retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserCredit(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*UserCredit, error) {
	userCreditObj := &UserCredit{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_credits\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userCreditObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_credits")
	}

	if err = userCreditObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userCreditObj, err
	}

	return userCreditObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserCredit) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_credits provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userCreditColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userCreditInsertCacheMut.RLock()
	cache, cached := userCreditInsertCache[key]
	userCreditInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userCreditAllColumns,
			userCreditColumnsWithDefault,
			userCreditColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userCreditType, userCreditMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userCreditType, userCreditMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_credits\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_credits\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_credits")
	}

	if !cached {
		userCreditInsertCacheMut.Lock()
		userCreditInsertCache[key] = cache
		userCreditInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserCredit.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserCredit) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userCreditUpdateCacheMut.RLock()
	cache, cached := userCreditUpdateCache[key]
	userCreditUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userCreditAllColumns,
			userCreditPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_credits, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_credits\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userCreditPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userCreditType, userCreditMapping, append(wl, userCreditPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_credits row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_credits")
	}

	if !cached {
		userCreditUpdateCacheMut.Lock()
		userCreditUpdateCache[key] = cache
		userCreditUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userCreditQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_credits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_credits")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserCreditSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userCreditPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_credits\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userCreditPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userCredit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userCredit")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserCredit) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_credits provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userCreditColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userCreditUpsertCacheMut.RLock()
	cache, cached := userCreditUpsertCache[key]
	userCreditUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userCreditAllColumns,
			userCreditColumnsWithDefault,
			userCreditColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userCreditAllColumns,
			userCreditPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_credits, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userCreditPrimaryKeyColumns))
			copy(conflict, userCreditPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_credits\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userCreditType, userCreditMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userCreditType, userCreditMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_credits")
	}

	if !cached {
		userCreditUpsertCacheMut.Lock()
		userCreditUpsertCache[key] = cache
		userCreditUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserCredit record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserCredit) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserCredit provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userCreditPrimaryKeyMapping)
	sql := "DELETE FROM \"user_credits\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_credits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_credits")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userCreditQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userCreditQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_credits")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_credits")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserCreditSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userCreditBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userCreditPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_credits\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userCreditPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userCredit slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_credits")
	}

	if len(userCreditAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserCredit) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserCredit(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserCreditSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserCreditSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userCreditPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_credits\".* FROM \"user_credits\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userCreditPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserCreditSlice")
	}

	*o = slice

	return nil
}

// UserCreditExists checks if the UserCredit row exists.
func UserCreditExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_credits\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_credits exists")
	}

	return exists, nil
}

// Exists checks if the UserCredit row exists.
func (o *UserCredit) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserCreditExists(ctx, exec, o.ID)
}
